### PR TITLE
Prepare setup.py for Pypi

### PR DESCRIPTION
**Pull request by titilambert**
Hello,
I want to use Nuance python scripts for TTS/ASR/NLU but this lib is not on Pypi. So I got the @Enfenion 's fork, changed small stuff and pushed to Pypi.
The package is here: https://pypi.python.org/pypi/speex
Everybody can now use it with the following command line: ```pip install speex```

### CODE REVIEW

**Comment by samueldg** [comment]
I think it's a great idea to have this on pypi and stop relying on GitHub links whenever possible.

Couple of questions:
* Could you give someone at Nuance access to publish to the pypi package? Since this links to a repo in NuanceDev, we should be able to upload.
* @jasl8r is this implementation specific to Nuance? (E.g. I know for Opus we wrap the packets in frames for HTTP transport efficiency) If that's the case we should make this really clear in the README, since the `speex` package name is really generic.

**Comment by jasl8r** [comment]
There's nothing Nuance specific in it.

**Comment by titilambert** [comment]
@samueldg Of course I can ! I just need pypi usernames to add to this package...
BTW, could you create the tag 0.9.1 ? Thanks !

https://pypi.python.org/pypi/speex

**Comment by samueldg** [comment]
@titilambert My pypi username is `samueldg`. You can give me full access and then I'll merge this and create the `0.9.1` tag.

**Comment by titilambert** [comment]
@samueldg done !

**Comment by samueldg** [comment]
@titilambert I tagged [0.9.1](https://github.com/NuanceDev/pyspeex/releases/tag/0.9.1) now.

Thanks again for contributing!

**Comment by titilambert** [comment]
Thanks !

**Pull request merged**
